// src/pages/player/VideoPlayer.tsx
import { useEffect, useState } from "react";
import Headers from "../components/Headers";
import axios from "axios";
import flvjs from "flv.js";
import { Card, Subtitle2, Text, Title3 } from "@fluentui/react-components";
import Footers from "../components/Footer";

function VideoPlayer() {
  // 获取parms
  const params = new URLSearchParams(window.location.search);
  const videoID = params.get("videoID");
  // 加载数据
  const [videoDetail, setVideoDetail] = useState({
    Id: 0,
    Title: "Loading...",
    Description: "Loading...",
    UploadDate: "Loading...",
  });
  useEffect(() => {
    getVideoDetail(videoID, setVideoDetail);
  }, []);
  return (
    <div className="flex flex-col">
      <Headers components to="/onlineVideo" />
      <Bodies videoDetail={videoDetail} />
    </div>
  );
}

// Body
function Bodies(props: { videoDetail: any }) {
  useEffect(() => {
    // 文件名切割获取文件类型
    let videoSuffix = "mp4";
    if (props.videoDetail["VideoName"] !== undefined)
      videoSuffix = props.videoDetail["VideoName"].split(".")[1];

    if (!flvjs.isSupported() && videoSuffix === "flv") {
      alert("您的设备不支持播放flv,请更换浏览器或者使用其他设备");
    } else {
      // 使用flv.js播放视频
      const player = flvjs.createPlayer({
        type: videoSuffix,
        url: "/resource/upload/videos/" + props.videoDetail["VideoName"],
        isLive: false,
      });
      player.attachMediaElement(
        document.getElementById("videoPlayer") as HTMLVideoElement
      );
      player.load();
      player.play();
    }
  }, [props.videoDetail]);
  return (
    <div className="flex flex-col items-center md:items-start md:ml-24 md:mr-24 ml-2 mr-2 mt-4">
      <Title3 className="mb-4">{props.videoDetail.Title}</Title3>
      <div className="w-full flex flex-col lg:flex-row">
        <video
          id="videoPlayer"
          controls
          className="lg:w-3/4 w-full"
          autoPlay
        ></video>
        <Card
          className="lg:w-1/4 w-full lg:ml-4 mt-4 lg:mt-0"
          appearance="outline"
        >
          <div className="flex flex-col flex-1">
            <Subtitle2 className="lg:ml-2 lg:mt-2">视频简介</Subtitle2>
            <Text className="lg:m-2 m-1">{props.videoDetail.Description}</Text>
            <Subtitle2 className="lg:ml-2 lg:mt-2">发布日期</Subtitle2>
            <Text className="lg:m-2 m-1">{props.videoDetail.UploadDate.replace("Z", "").replace("T", " ")}</Text>
          </div>
        </Card>
      </div>
      <Footers />
    </div>
  );
}

// 获取数据详细信息
function getVideoDetail(id: any, setVideoDetail: any) {
  axios.get("/api/video/get-video?id=" + id).then((res) => {
    document.title = res.data.data.video.Title;
    setVideoDetail(res.data.data.video);
  });
}

export default VideoPlayer;

// src/layouts/player/VideoPlayer.vue
<script setup>

import AppBar from "@/components/AppBar.vue";
import {computed, ref} from "vue";
import {useDisplay} from "vuetify";
import axios from "axios";
import FooterBar from "@/components/FooterBar.vue";
import mpegts from "mpegts.js";

const is_show = ref(false)
const {mobile} = useDisplay()
const mob = computed(() => {
  return mobile.value
})
// 获取parms
const params = new URLSearchParams(window.location.search);
const videoID = params.get("id");
const videoDetail = ref({
  Id: 0,
  Title: "Loading...",
  Description: "Loading...",
  UploadDate: "Loading...",
})

function getVideoDetail(id) {
  axios.get("/api/video/get-video?id=" + id).then((res) => {
    document.title = res.data.data.video.Title;
    videoDetail.value = res.data.data.video;
  });
}

getVideoDetail(videoID)
</script>

<template>
  <v-app>
    <AppBar v-model:is_show="is_show"/>
    <FooterBar/>
    <v-navigation-drawer v-model="is_show" :location="mob ? 'top' : 'left'">
      <v-list density="compact" nav>
        <v-list-item color="primary" prepend-icon="mdi-video" title="在线视频"
                     value="online-videos" to="/online-video" link></v-list-item>
        <v-list-item color="primary" prepend-icon="mdi-video-input-antenna" title="直播大厅"
                     value="live-room" to="/live-room" link></v-list-item>
      </v-list>
    </v-navigation-drawer>
    <v-main>
      <div class="flex flex-col items-center md:items-start md:ml-24 md:mr-24 mt-4">
        <h2 class="mb-4" style="text-align: center">{{ videoDetail.Title }}</h2>
        <div class="w-full flex flex-col lg:flex-row">
          <video
            id="videoPlayer"
            controls
            class="lg:w-3/4 w-full rounded"
            autoPlay
            :src="'/resource/upload/videos/' + videoDetail.VideoName"
          ></video>
          <v-card
            class="lg:w-1/4 lg:ml-4 lg:mt-0 ml-2 mr-2"
          >
            <div class="flex flex-col flex-1 m-2">
              <h3 class="lg:ml-2 lg:mt-2">视频简介</h3>
              <p class="lg:m-2 m-1">{{ videoDetail.Description }}</p>
              <h3 class="lg:ml-2 lg:mt-2">发布日期</h3>
              <p class="lg:m-2 m-1">{{ videoDetail.UploadDate.replace("Z", "").replace("T", " ") }}</p>
            </div>
          </v-card>
        </div>
      </div>
    </v-main>
  </v-app>
</template>

<style scoped>

</style>
