// src/views/LiveRoom.vue
<script></script>
<template>
  <div class="coil ml-4 mt-4">
    <div class="text-h5 font-weight-bold">直播大厅</div>
    <div class="flex flex-wrap mt-4" v-if="items.length !== 0">
      <div v-for="item in items" :key="item.id" class="2xl:w-1/5 xl:w-1/4 lg:w-1/3 md:w-1/3 w-full pr-4 coil mb-2">
        <v-card @click="click_item(item)">
          <v-img :src="'/resource/upload/images/' + item.HeadImage" class="rounded w-full aspect-video" cover/>
          <div class="flex items-center mt-2">
            <div class="text-subtitle-2 ml-2 mr-2 truncate">{{ item.Title }}</div>
            <v-badge v-if="item.LiveState" content="直播中" color="success" class="ml-4"></v-badge>
            <v-badge v-else content="无信号" color="error" class="ml-4"></v-badge>
          </div>
          <div class="text-subtitle-2 font-weight-light ml-2 mb-2 mr-2 truncate">{{ item.Description }}</div>
        </v-card>
      </div>
    </div>
    <div v-else-if="!loading" class="flex flex-col justify-center items-center w-full">
      <v-icon size="x-large">mdi-inbox-outline</v-icon>
      <div class="text-h6 font-weight-bold mt-2">啊嘞，这里毛也没有啊！</div>
    </div>
  </div>
</template>
<script setup>
import {ref, onMounted} from 'vue'
import axios from 'axios'
import router from "@/router";

const items = ref([])
const loading = ref(true)
onMounted(() => {
  axios.get('/api/live/get-live-list').then((res) => {
    items.value = res.data.data.list
    loading.value = false
  })
})
function click_item(item) {
  router.push("/live-player/?id=" + item.Id)
}
</script>

// src/pages/index/LiveRoom.tsx
import axios from "axios";
import { useEffect, useState } from "react";
import Skeletons from "../components/Skeletons";
import {
  Badge,
  Body1,
  Body2,
  Card,
  Title2,
  Title3,
} from "@fluentui/react-components";

function LiveRoom() {
  const [livesList, setLiveList] = useState([]);
  const [loadSuccess, setLoadSuccess] = useState(false);
  // 获取并解析数据
  useEffect(() => {
    getLives(setLiveList, setLoadSuccess);
  }, []);
  return (
    <div className="flex flex-col">
      <Title2 className="mb-2 ml-2">{"直播大厅"}</Title2>
      {loadSuccess ? <LiveList livesList={livesList} /> : <Skeletons />}
    </div>
  );
}

// 数据卡片
function LiveList(props: { livesList: any }) {
  return (
    <div>
      {props.livesList.length === 0 ? (
        <div className="flex justify-center">
          <Body2>暂无数据</Body2>
        </div>
      ) : null}
      {props.livesList.map((item: any, key: any) => {
        return (
          <div key={key}>
            <Card
              onClick={() => {
                itemClick(item.Id);
              }}
              appearance="subtle"
            >
              <div className="flex md:flex-row flex-col">
                <img
                  src={"/resource/upload/images/" + item.HeadImage}
                  className="rounded md:w-64 w-full md:h-36"
                />
                <div className="flex flex-col justify-center md:ml-4 mt-1">
                  <div className="flex items-center">
                    <Title3>{item.Title}</Title3>
                    {item.LiveState == true ? (
                      <Badge
                        appearance="filled"
                        className="ml-2"
                        color="success"
                      >
                        直播中
                      </Badge>
                    ) : (
                      <Badge
                        appearance="filled"
                        className="ml-2"
                        color="danger"
                      >
                        无信号
                      </Badge>
                    )}
                  </div>

                  <Body1 className="md:mt-1">{item.Description}</Body1>
                  <Body1>
                    {item.SubmitDate.replace("T", " ").replace("Z", " ")}
                  </Body1>
                </div>
              </div>
            </Card>
          </div>
        );
      })}
    </div>
  );
}

// 获取数据
function getLives(
  setLiveList: React.Dispatch<React.SetStateAction<never[]>>,
  setLoadSuccess: React.Dispatch<React.SetStateAction<boolean>>
) {
  axios.get("/api/live/get-live-list").then((res) => {
    // res.data 反向排序
    res.data.data.list.reverse();
    setLiveList(res.data.data.list);
    setLoadSuccess(true);
  });
}

// item点击事件
function itemClick(id: number) {
  // 跳转到视频详情页
  window.location.href = "/livePlayer?liveID=" + id;
}

export default LiveRoom;
